# Base image

FROM python:3.11-slim

# Set working directory

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements

COPY requirements.txt .

# Install Python dependencies

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy project files

COPY . .

# Expose Streamlit port

EXPOSE 8501

# Streamlit config

ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0

# Run app

CMD ["streamlit", "run", "app.py"]
